services:
  postgres:
    image: postgres:latest
    container_name: punct_bank_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql